name: docs-utils

services:
  docs-utils:
    container_name: docs-utils
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - npm_public

networks:
  npm_public:
    external: true
