name: Deploy JSDoc to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and deploy with Docker Compose
        run: |
          docker compose down --remove-orphans || true
          docker compose up -d --build

      - name: Setup Node for Gitea Packages
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://gitea.7u.pl/api/packages/gkucmierz/npm/'
          scope: '@gkucmierz'

      - name: Publish to Native Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITEA_TOKEN }}
